eurofurence/reg-attendee-service

test/acceptance/attendee_acc_test.go, web/controller/attendeectl/validation.go, web/controller/attendeectl/validation_test.go
New implementation for validating nicknames to fix #3.
=> Bugfix for #3 fix nickname validation

docs/config-template.yaml, internal/repository/config/structure.go, internal/repository/config/validation.go, internal/service/attendeesrv/dues.go, test/testconfig-needlogin-before-target-staffreg.yaml, test/testconfig-needlogin-before-target.yaml, test/testconfig-needlogin-staffreg.yaml, test/testconfig-needlogin.yaml, test/testconfig-public-before-target-staffreg.yaml, test/testconfig-public-before-target.yaml, test/testconfig-public-staffreg.yaml, test/testconfig-public.yaml
- add userinfo endpoint config field
- add currency config field and default to EUR
- specify prices in cents like in payment service
=> Issue 64 unify config

.gitignore, internal/repository/paymentservice/interface.go, internal/repository/paymentservice/mock.go, internal/service/attendeesrv/dues.go, internal/service/attendeesrv/status.go, test/acceptance/status_acc_test.go, test/acceptance/utils_test.go, test/contract/consumer/mail_ctr_test.go, test/contract/consumer/pacts/attendeeservice-paymentservice.json, test/contract/consumer/pacts/mailservice-paymentservice.json, test/contract/consumer/payment_ctr_test.go, test/contract/consumer/setup_ctr_test.go
After finding typos and mismatches in the Dtos that caused all dues to be created for 0€, maybe it's time we finally did this.
=> feat(#71): add payment service consumer contract test

api/openapi-spec/openapi.yaml, docs/config-template.yaml, internal/repository/config/config.go, internal/repository/config/loading_test.go, internal/repository/config/structure.go, internal/repository/config/validation.go, internal/repository/database/inmemorydb/implementation.go, internal/service/attendeesrv/addinfo.go, internal/service/attendeesrv/interfaces.go, internal/service/attendeesrv/permissions.go, internal/service/attendeesrv/search.go, internal/service/attendeesrv/search_test.go, internal/service/attendeesrv/status.go, internal/web/app/server.go, internal/web/controller/addinfoctl/addinfoctl.go, internal/web/controller/attendeectl/config_test.go, test/acceptance/admin_acc_test.go, test/acceptance/status_acc_test.go, test/acceptance/utils_test.go, test/acceptance/webhook_acc_test.go, test/contract/producer/setup_ctr_test.go, test/testconfig-base.yaml
- closes #81 
- closes #82 
- closes #95 (will add tests at later time)
=> Issue 81 82 95 missing features

internal/service/attendeesrv/attendeesrv.go, internal/service/attendeesrv/dues.go
=> Issue 104 missing packages: found the cause

internal/web/controller/adminctl/adminctl.go, internal/web/controller/attendeectl/attendeectl.go
=> fix(#111): remove undocumented admin role check endpoint

docs/config-template.yaml, internal/repository/config/structure.go, internal/repository/config/validation.go, internal/repository/config/validation_test.go, internal/web/controller/adminctl/adminctl.go, internal/web/controller/banctl/banctl.go, internal/web/controller/statusctl/statusctl.go, internal/web/filter/authcheck.go, test/acceptance/utils_test.go, test/testconfig-base.yaml
=> feat(#113): restrict admin requests to local

docs/config-template.yaml, internal/web/controller/attendeectl/validation.go
=> Issue 121 fix language list, validate pronouns field length

internal/service/attendeesrv/attendeesrv.go, internal/service/attendeesrv/interfaces.go, internal/web/controller/attendeectl/attendeectl.go, internal/web/controller/attendeectl/config_test.go, internal/web/controller/attendeectl/validation.go, internal/web/controller/attendeectl/validation_test.go, test/acceptance/attendee_acc_test.go, test/contract/producer/setup_ctr_test.go
- closes #125 
Should add a few more test cases to cover the conditions
=> feat(#125): reject package remove by user after payment

internal/service/attendeesrv/status.go, test/acceptance/status_acc_test.go
=> fix(#135): allow sending approved with auto-progress to (partially) paid

internal/repository/authservice/client.go, internal/web/middleware/security.go
=> small fixes from testing

internal/service/attendeesrv/attendeesrv.go, internal/web/controller/attendeectl/validation_test.go, test/acceptance/attendee_acc_test.go, test/testconfig-base.yaml
=> fix(#139): fix package change validation after payment

api/openapi-spec/openapi.yaml, docs/config-template.yaml, internal/service/attendeesrv/interfaces.go, internal/service/attendeesrv/status.go, internal/web/controller/attendeectl/config_test.go, internal/web/controller/statusctl/statusctl.go, test/acceptance/status_acc_test.go, test/acceptance/utils_test.go, test/contract/producer/setup_ctr_test.go
- closes #128 
also fixes config template to match current situation
=> feat(#128): add admin endpoint for status mail resend

internal/repository/database/inmemorydb/match.go, internal/repository/database/mysqldb/searchquery.go, internal/repository/database/mysqldb/searchquery_test.go, internal/service/attendeesrv/dues.go, internal/service/attendeesrv/dues_test.go, internal/service/attendeesrv/status.go, test/acceptance/admin_acc_test.go, test/acceptance/attendee_acc_test.go, test/acceptance/status_acc_test.go, test/acceptance/webhook_acc_test.go
=> fix(#147): calculate correct due date and send correct mails

.github/workflows/go.yml, api/openapi-spec/openapi.yaml, docs/config-template.yaml, go.mod, internal/repository/config/config.go, internal/repository/config/structure.go, internal/web/controller/addinfoctl/addinfoctl.go, test/acceptance/addinfo_acc_test.go, test/acceptance/admin_acc_test.go, test/testconfig-base.yaml
- need a PR for testing action changes
- closes #102 
- closes #153
=> action cleanup (#153) and finally add missing acctests (#102)

api/openapi-spec/openapi.yaml, internal/api/v1/attendee/api.go, internal/service/attendeesrv/adminsrv.go, internal/service/attendeesrv/attendeesrv.go, internal/service/attendeesrv/interfaces.go, internal/service/attendeesrv/status.go, internal/web/controller/adminctl/adminctl.go, internal/web/controller/attendeectl/attendeectl.go, internal/web/controller/attendeectl/config_test.go, internal/web/controller/attendeectl/validation.go, internal/web/controller/statusctl/statusctl.go, test/acceptance/admin_acc_test.go, test/acceptance/attendee_acc_test.go, test/contract/producer/setup_ctr_test.go
=> Issue 154 155 status due dates

api/openapi-spec/openapi.yaml, internal/service/attendeesrv/addinfo.go, internal/service/attendeesrv/interfaces.go, internal/service/attendeesrv/permissions.go, internal/web/controller/adminctl/adminctl.go, internal/web/controller/attendeectl/config_test.go, internal/web/middleware/security.go, internal/web/middleware/security_test.go, test/acceptance/admin_acc_test.go, test/acceptance/status_acc_test.go, test/contract/producer/setup_ctr_test.go
=> support for new regdesk & sponsordesk UI

.github/workflows/docker.yml, Dockerfile
=> feat(#167): add docker build

cmd/datagen/datagen.go, internal/repository/config/config.go, internal/repository/config/loading.go, internal/service/attendeesrv/generate.go, internal/service/attendeesrv/generate_test.go, internal/service/attendeesrv/interfaces.go, internal/web/app/application.go, internal/web/controller/attendeectl/config_test.go
=> feat(#177): add fake reg data generator

api/openapi-spec/openapi.yaml, docs/config-template.yaml, internal/repository/config/config.go, internal/repository/config/structure.go, internal/service/attendeesrv/addinfo.go, internal/service/attendeesrv/interfaces.go, internal/service/attendeesrv/permissions.go, internal/web/controller/addinfoctl/addinfoctl.go, internal/web/controller/attendeectl/config_test.go, test/acceptance/addinfo_acc_test.go, test/testconfig-base.yaml
- closes #182 
See config-template.yaml and read #182 to see what this does.
=> feat(#182): improve addnl info permission handling

docs/config-template.yaml
=> feat(#197): configuration updates for local version

api/openapi-spec/openapi.yaml, internal/web/controller/adminctl/adminctl.go, test/acceptance/admin_acc_test.go
=> allow filtering fields for user permission finds

.gitignore, cmd/staffbadges/config.go, cmd/staffbadges/idpquery.go, cmd/staffbadges/regsysquery.go, cmd/staffbadges/staffbadges.go
- closes #225 
This PR includes a separate runnable command to control staff and director flags.
=> Issue 225 badge flags tooling

api/openapi-spec/openapi.yaml, internal/api/v1/addinfo/api.go, internal/repository/database/dbrepo/interface.go, internal/repository/database/historizeddb/implementation.go, internal/repository/database/inmemorydb/implementation.go, internal/repository/database/mysqldb/implementation.go, internal/service/attendeesrv/addinfo.go, internal/service/attendeesrv/interfaces.go, internal/web/controller/addinfoctl/addinfoctl.go, internal/web/controller/attendeectl/config_test.go, test/acceptance/addinfo_acc_test.go
=> read all add-info endpoint

internal/repository/paymentservice/interface.go, internal/service/attendeesrv/dues.go, test/acceptance/status_acc_test.go, test/acceptance/utils_test.go
=> fill reason field on dues transactions

internal/web/controller/attendeectl/attendeectl.go
=> correctly log success status for attendee update

api/openapi-spec/openapi.yaml, docs/config-template.yaml, go.mod, internal/api/v1/attendee/api.go, internal/repository/config/structure.go, internal/repository/config/validation.go, internal/repository/config/validation_test.go, internal/web/controller/attendeectl/attendeectl.go, internal/web/controller/attendeectl/validation.go, internal/web/controller/attendeectl/validation_test.go, test/acceptance/attendee_acc_test.go, test/testconfig-base.yaml
- closes #239 
(I hope I've got everything this time)
=> Issue 239 multi package missing stuff

docs/config-template.yaml
=> small fixes

internal/service/attendeesrv/adminsrv.go, internal/service/attendeesrv/attendeesrv.go, internal/service/attendeesrv/interfaces.go, internal/service/attendeesrv/status.go, internal/web/controller/attendeectl/config_test.go, internal/web/controller/statusctl/statusctl.go, internal/web/util/ctxvalues/accessors.go, internal/web/util/ctxvalues/accessors_test.go
=> deal with timeouts caused by sending email taking too long

internal/web/util/ctxvalues/accessors.go
=> also copy logger to async context so log lines show up

api/openapi-spec/openapi.yaml, internal/repository/database/inmemorydb/implementation.go, internal/service/attendeesrv/addinfo.go, internal/service/attendeesrv/interfaces.go, internal/web/controller/addinfoctl/addinfoctl.go, internal/web/controller/attendeectl/config_test.go, test/acceptance/addinfo_acc_test.go
- implement #233 
- see acceptance tests and API specification changes for details
=> Issue 233 global add info
